version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && cp logo.png static/img/logo.png && gunicorn --certfile=/etc/certs/localhost.crt --keyfile=/etc/certs/localhost.key kanban.wsgi:application --bind 0.0.0.0:443"
    container_name: kanban_gunicorn
    volumes:
      - ./config/nginx/certs/:/etc/certs
      - ./src/static:/src/static
    expose:
      - "443"
  nginx:
    image: nginx:latest
    container_name: kanban_nginx
    ports:
      - "443:443"
      - "8000:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
      - ./src/static:/static
    depends_on:
      - web
