version: '3'

services:

  db:
    image: mysql:8.0.21
    container_name: kanban_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=T59PNfzNSb
      - MYSQL_DATABASE=kanban_data

  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && cp logo.png static/img/logo.png && gunicorn --certfile=/etc/certs/localhost.crt --keyfile=/etc/certs/localhost.key kanban.wsgi:application --bind 0.0.0.0:443"
    container_name: kanban_gunicorn
    volumes:
      - ./config/nginx/certs/:/etc/certs
      - ./src/static:/src/static
    expose:
      - "443"
    depends_on:
      - db
 
  nginx:
    image: nginx:latest
    container_name: kanban_nginx
    ports:
      - "443:443"
      - "8000:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
      - ./src/static:/static
    depends_on:
      - web
